### ISSUE TITLE
Question about Stencil Playwright

### ISSUE THREAD

**Issue by MathisPct** [alicewriteswrongs/stencil-playwright-example#1]
Hello I have a question about Stenciljs playwright

When I try to launch test by using the command `npx playwright test`, I have a timeout error on your project.

`Error: Timed out waiting 60000ms from config.webServer.`

Do you encounter this problem ? **I try to add Playwright as test engine on my project and I have the same problem

I use your repository as example, even if you use a pretty old version of `@stencil/playwright`. 

Enjoy your day :) And thank you by advance for your help

**Comment by alicewriteswrongs** [comment]
Hey I don't work on Stencil anymore - try the community discussion board https://github.com/ionic-team/stencil/discussions
